CMAKE_MINIMUM_REQUIRED(VERSION 4.1.1)

PROJECT(Roxy LANGUAGES CXX)

SET(CMAKE_CXX_STANDARD 23)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)
SET(CMAKE_CXX_EXTENSIONS OFF)

SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib")
SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib")

OPTION(ROXY_ENABLE_ASSERT    "Enable C Style Assert"      ON)
OPTION(ROXY_ENABLE_NODISCARD "Enable Attribute Nodiscard" ON)
OPTION(ROXY_ENABLE_INLINE    "Enable Force Inline"        ON)

if(ROXY_ENABLE_ASSERT)
    ADD_COMPILE_DEFINITIONS(ROXY_ENABLE_ASSERT=1)
endif()
if(ROXY_ENABLE_NODISCARD)
    ADD_COMPILE_DEFINITIONS(ROXY_ENABLE_NODISCARD=1)
endif()
if(ROXY_ENABLE_INLINE)
    ADD_COMPILE_DEFINITIONS(ROXY_ENABLE_INLINE=1)
endif()

ADD_SUBDIRECTORY(External)
ADD_SUBDIRECTORY(Source)
