CMAKE_MINIMUM_REQUIRED(VERSION 4.1.1)

PROJECT(Roxy LANGUAGES C CXX)

SET(CMAKE_CXX_STANDARD 23)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)
SET(CMAKE_CXX_EXTENSIONS OFF)

SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib")
SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib")

OPTION(ROXY_ENABLE_ASSERT    "Enable C Style Assert"      ON)
OPTION(ROXY_ENABLE_NODISCARD "Enable Attribute Nodiscard" ON)
OPTION(ROXY_ENABLE_INLINE    "Enable Force Inline"        ON)
OPTION(ROXY_BUILD_TEST       "Build Tests"                ON)
OPTION(ROXY_ENABLE_SIMD      "Enable SIMD"                ON)

IF(ROXY_ENABLE_ASSERT)
    ADD_COMPILE_DEFINITIONS(ROXY_ENABLE_ASSERT=1)
ENDIF()
IF(ROXY_ENABLE_NODISCARD)
    ADD_COMPILE_DEFINITIONS(ROXY_ENABLE_NODISCARD=1)
ENDIF()
IF(ROXY_ENABLE_INLINE)
    ADD_COMPILE_DEFINITIONS(ROXY_ENABLE_INLINE=1)
ENDIF()
IF(ROXY_BUILD_TEST)
    ENABLE_TESTING()
ENDIF()
IF(ROXY_ENABLE_SIMD)
    ADD_COMPILE_DEFINITIONS(ROXY_ENABLE_SIMD=1)
ENDIF()
IF (MSVC)
    ADD_COMPILE_DEFINITIONS(ROXY_IS_MSVC=1)
ENDIF()

ADD_SUBDIRECTORY(External)
ADD_SUBDIRECTORY(Source)
