IF(MSVC)
    ADD_COMPILE_OPTIONS(/GR- /EHs- /EHc- /W4 /WX /wd4702 /nologo)
    ADD_COMPILE_DEFINITIONS("_HAS_EXCEPTIONS=0")
ELSE()
    ADD_COMPILE_OPTIONS(-fno-rtti -fno-exceptions -Wall -Wextra -Werror)
ENDIF()

# Plugin
ADD_SUBDIRECTORY(Plugin)

# Roxy
ADD_EXECUTABLE(Roxy Roxy.cpp)

TARGET_LINK_LIBRARIES(Roxy PRIVATE
    RoxyAlloc
    RoxyChrono
    RoxyLog
    RoxyFmt
    RoxySTD
    RGFW::RGFW
)

IF(WIN32)
ELSEIF(APPLE)
    FIND_LIBRARY(COCOA_FRAMEWORK Cocoa REQUIRED)
    FIND_LIBRARY(OPENGL_FRAMEWORK OpenGL REQUIRED)
    FIND_LIBRARY(CORE_VIDEO_FRAMEWORK CoreVideo REQUIRED)
    FIND_LIBRARY(QUARTZ_CORE_FRAMEWORK QuartzCore REQUIRED)
    FIND_LIBRARY(CORE_GRAPHICS_FRAMEWORK CoreGraphics REQUIRED)
    TARGET_LINK_LIBRARIES(Roxy PRIVATE
        ${COCOA_FRAMEWORK}
        ${OPENGL_FRAMEWORK}
        ${CORE_VIDEO_FRAMEWORK}
        ${QUARTZ_CORE_FRAMEWORK}
        ${CORE_GRAPHICS_FRAMEWORK}
    )
ELSEIF(UNIX)
    FIND_PACKAGE(X11 REQUIRED)
    TARGET_LINK_LIBRARIES(Roxy PRIVATE
        X11::X11
        X11::Xrandr
        X11::Xinerama
        X11::Xcursor
        X11::Xi
    )
    FIND_PACKAGE(OpenGL REQUIRED)
    TARGET_LINK_LIBRARIES(Roxy PRIVATE OpenGL::GL)
ENDIF()
