if(MSVC)
    ADD_COMPILE_OPTIONS(/W4 /WX /wd4530)
endif()

# Core
ADD_LIBRARY(Core STATIC Core.h Core.cpp)
TARGET_INCLUDE_DIRECTORIES(Core PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
TARGET_COMPILE_OPTIONS(Core PUBLIC /GR- /EHs- /EHa-)
TARGET_COMPILE_DEFINITIONS(Core PUBLIC _HAS_EXCEPTIONS=0)
TARGET_PRECOMPILE_HEADERS(Core PUBLIC Core.h)

# ECS
ADD_LIBRARY(ECS STATIC ECS.h ECS.cpp)
TARGET_INCLUDE_DIRECTORIES(ECS PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
TARGET_LINK_LIBRARIES(ECS PRIVATE Core)

# Roxy
ADD_EXECUTABLE(Roxy Roxy.h Roxy.cpp)
