name: linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - c_compiler: gcc
            cpp_compiler: g++
            build_type: Debug
          - c_compiler: gcc
            cpp_compiler: g++
            build_type: Release
          - c_compiler: clang
            cpp_compiler: clang++
            build_type: Debug
          - c_compiler: clang
            cpp_compiler: clang++
            build_type: Release

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build \
            libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev

      - name: Get CMake 4.1.1
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "4.1.1"

      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build
          -G "Ninja Multi-Config"
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DROXY_BUILD_UNIT_TEST=ON
          -DCMAKE_CXX_STANDARD=23
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -C ${{ matrix.build_type }} --output-on-failure
